//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRentalApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class login
    {
        public int id { get; set; }
        [DisplayName("Username")]
        [Required(ErrorMessage = "Username is not null")]
        public string username { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is not null")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [DisplayName("Remember me")]
        public bool remember_me { get; set; }
    }
}
